base-files: fix resetting may fail on rootfs full
(cherry picked from commit c82edc0d5ecd8d7732b2132d45f99d0a831b5e8c)

diff --git a/target/linux/realtek/base-files/usr/sbin/jffs2reset b/target/linux/realtek/base-files/usr/sbin/jffs2reset
--- a/target/linux/realtek/base-files/usr/sbin/jffs2reset
+++ b/target/linux/realtek/base-files/usr/sbin/jffs2reset
@@ -1,5 +1,6 @@
 #!/bin/sh
 
+OVERLAY_LABEL="etc"
 CONFIRM=n
 REBOOT=n
 
@@ -12,16 +13,40 @@ confirm()
   return 1
 }
 
+do_reset_nofs()
+{
+  local OVERLAY_DEV=
+  for item in `cat /proc/cmdline`; do
+    case $item in
+      overlay=*)		OVERLAY_DEV=${item:8};;
+    esac
+  done
+  if [ -z "$OVERLAY_DEV" ]; then
+    OVERLAY_DEV=`blkid -L $OVERLAY_LABEL | grep /mmcblk0p`
+  fi
+  if [ -z "$OVERLAY_DEV" ]; then
+    echo "overlay not found by cmdline or label, maybe we are already in resetting?" >&2
+    return 0
+  fi
+
+  echo "RESET" | dd of=$OVERLAY_DEV bs=512 count=1 conv=notrunc
+  echo 3 > /proc/sys/vm/drop_caches
+  return 0
+}
+
 do_reset()
 {
-  mount_root || ( echo "/overlay mount failed!" ; exit 1 )
   if [ -f /.recovery_mode ]; then
+    mount_root || ( echo "/overlay mount failed!" ; exit 1 )
     rm -rf /overlay/upper
     mkdir /overlay/upper
     sync /overlay
   else
-    touch /overlay/.reset
-    sync /overlay/.reset
+    if touch /overlay/.reset; then
+      sync /overlay
+    else
+      do_reset_nofs
+    fi
   fi
   [ "$REBOOT" = "y" ] && reboot
   exit 0
