target/rockchip: add Radxa E52C/E54C
SoC: RK3582
Signed-off-by: Liangbin Lian <jjm2473@gmail.com>

diff --git a/target/linux/rockchip/armv8/base-files/lib/preinit/04_board b/target/linux/rockchip/armv8/base-files/lib/preinit/04_board
--- a/target/linux/rockchip/armv8/base-files/lib/preinit/04_board
+++ b/target/linux/rockchip/armv8/base-files/lib/preinit/04_board
@@ -40,4 +40,18 @@ preinit_gpio() {
 	esac
 }
 
+preinit_rebind_drivers() {
+	case $(board_name) in
+	radxa,e54c)
+		# rebind e54c hym8563 if previously bound failed
+		[ -e /sys/bus/i2c/drivers/rtc-hym8563/4-0051 ] || { echo "4-0051" > /sys/bus/i2c/drivers/rtc-hym8563/bind; }
+	;;
+	radxa,e52c)
+		# rebind e52c hym8563 if previously bound failed
+		[ -e /sys/bus/i2c/drivers/rtc-hym8563/5-0051 ] || { echo "5-0051" > /sys/bus/i2c/drivers/rtc-hym8563/bind; }
+	;;
+	esac
+}
+
 boot_hook_add preinit_main preinit_gpio
+boot_hook_add preinit_main preinit_rebind_drivers
